version: "3.5"
services:
  arangoproxy:
    container_name: arangoproxy
    image: arangoproxy
    build:
      context: .
      target: arangoproxy
    networks:
      docs_net:
        ipv4_address: 192.168.129.129
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./toolchain:/home
      - ./site/data:/etc/arangoproxy
    environment:
      - ARANGOPROXY_ARGS

  site:
    container_name: site
    image: site
    depends_on:
      - "arangoproxy"
    build:
      context: .
      target: hugo
    ports:
      - "1313:1313"
    networks:
      docs_net:
        ipv4_address: 192.168.129.130
    volumes:
      - ./site:/site
      - ./toolchain:/home
    environment:
      - HUGO_ENV
      - HUGO_URL

networks:
  docs_net:
    name: docs_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.129.0/24
          gateway: 192.168.129.1
