version: "3.5"
services:
  arango_single_3_10:
    container_name: arango_single_3_10
    image: arangodb/enterprise:latest
    networks:
      docs_net:
        ipv4_address: 192.168.129.5
    environment:
      - ARANGO_NO_AUTH=1

  arango_cluster_3_10_1:
    container_name: arango_cluster_3_10_1
    image: arangodb/enterprise:latest
    networks:
      docs_net:
        ipv4_address: 192.168.129.5
    environment:
      - ARANGO_NO_AUTH=1

networks:
  docs_net:
    name: docs_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.129.0/24
          gateway: 192.168.129.1
