version: "3.5"
services:
  site-frontend:
    container_name: docs_plain-build
    image: arangodb/docs-hugo:site-amd64
    networks:
      docs_plain_net:
        ipv4_address: 192.168.130.130
    ports:
      - "1313:1313"
    volumes:
      - ../../../:/home/
    environment:
      HUGO_URL: ${HUGO_URL:-http://localhost}
      HUGO_ENV: ${HUGO_ENV:-frontend}
      ENV: ${ENV:-local}


  arangoproxy-frontend:
    container_name: docs_arangoproxy-frontend
    image: arangodb/docs-hugo:arangoproxy-amd64
    networks:
      docs_plain_net:
        ipv4_address: 192.168.130.129
    volumes:
      - ../../../:/home/
    environment:
      HUGO_URL: ${HUGO_URL:-http://localhost}
      HUGO_ENV: ${HUGO_ENV:-frontend}
      ENV: ${ENV:-local}


networks:
  docs_plain_net:
    driver: bridge
    name: docs_plain_net
    ipam:
          driver: default
          config:
              - subnet: "192.168.130.0/24"
                gateway: "192.168.130.1"