webserver: ':8080'
logFile: log.txt
datasetsFile: '../internal/aql/datasets.json'
cache: '/home/site/data/cache.json'
repositories:
  - name: stable
    image: testimage
    version: "3.10"
    url: http://192.168.129.2:8529
