datasetsFile: '../internal/utils/datasets.json'
cache: '/home/site/data/'
debug: false
repositories:
  - type: single
    version: "3.10"
    url: http://192.168.129.3:8529
  - type: cluster
    version: "3.10"
    url: http://192.168.129.2:8529
  - type: single
    version: "3.11"
    url: http://192.168.129.5:8529
  - type: cluster
    version: "3.11"
    url: http://192.168.129.4:8529
  - type: single
    version: "3.12"
    url: http://192.168.129.7:8529
  - type: cluster
    version: "3.12"
    url: http://192.168.129.6:8529
