deploy:
  docker:
    - image: williamjackson/netlify-cli
  resource_class: small
  steps:
    - attach_workspace:
        at: .
    - run:
        name: Deploy to netlify
        command:  /home/node/docker-netlify-cli/node_modules/.bin/netlify deploy --dir=docs-hugo/site/public --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --alias << pipeline.parameters.deploy-url >>
        no_output_timeout: 1h

clone-docs-and-merge:
  description: Clone docs and merge main content before generate
  steps:
    - run: 
        name: Clone docs repo
        command: |
          git clone git@github.com:arangodb/docs-hugo.git --branch $CIRCLE_BRANCH
          cd docs-hugo/
          git fetch --all
          git pull --all
          git merge --no-edit -X theirs origin/frontend-preview 
          cd ../

commit:
  description: Commit generated content
  parameters:
    commit-generated:
      type: boolean
      default: false
    create-pr:
      type: boolean
      default: false
    pr-branch:
      type: string
      default: ""
  steps:
    - run:
        name: Commit generated files
        command: |
          if [ "<< parameters.commit-generated >>" = true ] ; then
            if [ "<< parameters.create-pr >>" = true ]; then
              cd docs-hugo/
              git checkout -b << parameters.pr-branch >>-$CIRCLE_BUILD_NUM
            fi

            cd /home/circleci/project/docs-hugo/site
            git config user.email "daniele@arangodb.com"
            git config user.name "CircleCI Job"
            git add data/ content/
            git commit --allow-empty -m "[skip ci] Automatic commit of generated files from CircleCI"

            if [ "<< parameters.create-pr >>" = true ]; then
              git push -u origin << parameters.pr-branch >>-$CIRCLE_BUILD_NUM
              curl -X POST https://candid-daffodil-f96315.netlify.app/.netlify/functions/circleci \
                --header 'docs-webhook-event: scheduled-create-pr' \
                --header "docs-branch-name: << parameters.pr-branch >>-$CIRCLE_BUILD_NUM" \
                --header "docs-pr-title: [CircleCI Generated] << pipeline.parameters.workflow >>-$CIRCLE_BUILD_NUM" \
                --header "docs-pr-body: Automatically generated content from CircleCI << pipeline.parameters.workflow >> workflow"
            else
              git push
            fi
          fi