create-docs-images:
  parameters:
    architecture:
      type: string
      default: "amd64"
    executor:
      type: string
      default: "medium"
  machine:
    docker_layer_caching: true
    image: ubuntu-2004:current
    resource_class: << parameters.executor >>
  steps:
    - run: 
        name: Clone docs repo
        command: |
          git clone --depth 1 https://github.com/arangodb/docs-hugo.git --branch $CIRCLE_BRANCH
    - run: 
        name: Create docker images
        command: |
          cd docs-hugo/toolchain/docker
          export DOCKER_BUILDKIT=1
          docker build -t arangodb/docs-hugo:site-<< parameters.architecture >> --target hugo .
          docker build -t arangodb/docs-hugo:arangoproxy-<< parameters.architecture >> --target arangoproxy .
          docker build -t arangodb/docs-hugo:toolchain-<< parameters.architecture >> --target toolchain .

    - run: 
        name: Push docker images
        command: |
          cd docs-hugo/toolchain/docker
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

          docker push arangodb/docs-hugo:site-<< parameters.architecture >>
          docker push arangodb/docs-hugo:arangoproxy-<< parameters.architecture >>
          docker push arangodb/docs-hugo:toolchain-<< parameters.architecture >>