build-with-generated:
  parameters:
    arangodb-3_10:
      type: string
      default: ""
    arangodb-3_11:
      type: string
      default: ""
    arangodb-3_12:
      type: string
      default: ""  
    generators:
      type: string
      default: examples
    commit-generated:
      type: boolean
      default: false
    create-pr:
      type: boolean
      default: false
    pr-branch:
      type: string
      default: ""
  machine:
    image: ubuntu-2004:current
  resource_class: xlarge
  steps:
    - add_ssh_keys:
        fingerprints:
          - "7a:1d:7f:0a:70:eb:2b:7d:25:10:9b:e8:dc:04:53:9a"
          - "28:4f:0b:b7:71:cd:39:ab:c0:33:65:4f:da:6a:cc:8e"
          - "bc:4d:f3:df:53:ad:22:d8:60:5d:10:d8:fd:74:d2:cd"
    - attach_workspace:
        at: .
    
    - run: ssh-keyscan github.com >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
    - clone-docs-and-merge
    - run:
        name: Set environment variables and launch toolchain
        command: |
          source docs-hugo/.circleci/utils.sh
          export ENV="circleci"
          export HUGO_URL=https://<< pipeline.parameters.deploy-url >>--docs-hugo.netlify.app
          export HUGO_ENV=examples
          export GENERATORS='<< parameters.generators >>'
          
          if [ "<< parameters.arangodb-3_10 >>" != "" ] ; then
            pull-branch-image << parameters.arangodb-3_10 >> "3.10"
            generate_setup-environment-var-branch << parameters.arangodb-3_10 >> "3_10"
          fi
          if [ "<< parameters.arangodb-3_11 >>" != "" ] ; then
            pull-branch-image << parameters.arangodb-3_11 >> "3.11"
            generate_setup-environment-var-branch << parameters.arangodb-3_11 >> "3_11"
          fi
          if [ "<< parameters.arangodb-3_12 >>" != "" ] ; then
            pull-branch-image << parameters.arangodb-3_12 >> "3.12"
            generate_setup-environment-var-branch << parameters.arangodb-3_12 >> "3_12"
          fi

          cd docs-hugo/toolchain/docker/amd64
          docker compose up
    - run:
        name: Upload summary on GitHub
        command: |
          cd /home/circleci/project/docs-hugo
          cat summary.md | curl -X POST -d@- https://candid-daffodil-f96315.netlify.app/.netlify/functions/circleci --header 'docs-webhook-event: create-summary' --header 'docs-branch-sha: '$CIRCLE_SHA1'' --header 'docs-check-name: generate-summary' --header 'docs-branch-name: '$CIRCLE_BRANCH''
        when: always
    
    - run:
        name: Create archive of generated files
        command: |
          cd docs-hugo/site/data
          tar -cvf /tmp/3.10-generated.tar 3.10/
          tar -cvf /tmp/3.11-generated.tar 3.11/
          tar -cvf /tmp/3.12-generated.tar 3.12/

    - store_artifacts:
        path: /tmp/3.10-generated.tar

    - store_artifacts:
        path: /tmp/3.11-generated.tar

    - store_artifacts:
        path: /tmp/3.12-generated.tar

    - commit:
        commit-generated: << parameters.commit-generated >>
        create-pr: << parameters.create-pr >>
        pr-branch: << parameters.pr-branch >>
    
    - persist_to_workspace:
        root: .
        paths:
          - docs-hugo/site/public

commit-generated:
  machine:
    image: ubuntu-2004:current
  resource_class: large
  steps:
    - add_ssh_keys:
        fingerprints:
          - "7a:1d:7f:0a:70:eb:2b:7d:25:10:9b:e8:dc:04:53:9a"
          - "28:4f:0b:b7:71:cd:39:ab:c0:33:65:4f:da:6a:cc:8e"
          - "bc:4d:f3:df:53:ad:22:d8:60:5d:10:d8:fd:74:d2:cd"
    - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
    - clone-docs-and-merge
    - run:
        name: Launch node script to get generated content from previous run
        command: |
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
          source ~/.bashrc   
          nvm install --lts 

          artifacts_job_id=$(node docs-hugo/.circleci/commit.js $CIRCLE_BRANCH)
          base_url=https://output.circle-artifacts.com/output/job/"$artifacts_job_id"/artifacts/0/tmp
          wget $base_url/3.10-generated.tar
          wget $base_url/3.11-generated.tar
          wget $base_url/3.12-generated.tar
          tar -xf 3.10-generated.tar -C docs-hugo/site/data/
          tar -xf 3.11-generated.tar -C docs-hugo/site/data/
          tar -xf 3.12-generated.tar -C docs-hugo/site/data/
    - commit:
        commit-generated: true
        create-pr: false
        pr-branch: ""