parameters:
  workflow:
    type: enum
    enum: [no-op, plain-build, generate, compile, generate-scheduled, commit-generated, generate-oasisctl, create-docs-images-amd64, create-docs-images-arm64]
    default: no-op
  
  deploy-url:
    type: string
    default: $CIRCLE_BRANCH

  generators:
    type: string
    default: ""

  version:
    type: string
    default: ""

  arangodb-branch:
    type: string
    default: ""

  arangodb-3_10:
    type: string
    default: ""

  arangodb-3_11:
    type: string
    default: ""

  arangodb-3_12:
    type: string
    default: ""

  commit-generated:
    type: boolean
    default: false

  create-pr:
    type: boolean
    default: false