plain-build: 
  parameters:
    deploy-url:
      type: string
      default: ""
  machine:
    image: ubuntu-2004:current
  resource_class: large
  steps:
    - run: 
        name: Clone docs repo
        command: |
          git clone --depth 1 git@github.com:arangodb/docs-hugo.git --branch $CIRCLE_BRANCH

    - run:
        name: Build site
        command: |
          export ENV="circleci"
          export HUGO_URL=https://<< parameters.deploy-url >>--docs-hugo.netlify.app
          export HUGO_ENV=frontend

          cd docs-hugo/toolchain/docker/amd64
          docker compose -f docker-compose.plain-build.yml up --abort-on-container-exit
    - run:
        name: Upload summary on GitHub
        command: |
          cd /home/circleci/project/docs-hugo
          cat summary.md | curl -X POST -d@- https://candid-daffodil-f96315.netlify.app/.netlify/functions/circleci --header 'docs-webhook-event: create-summary' --header 'docs-branch-sha: '$CIRCLE_SHA1'' --header 'docs-check-name: plain-build-summary'  --header 'docs-branch-name: '$CIRCLE_BRANCH''
        when: always

    - persist_to_workspace:
        root: .
        paths:
          - docs-hugo/site/public