version: "3.5"
services:
  site-frontend:
    container_name: plain-build
    image: site
    build:
      context: .
      target: hugo
    networks:
      docs_net:
        ipv4_address: 192.168.129.130
    volumes:
      - ../../:/home/
    environment:
      - HUGO_URL
      - HUGO_ENV

  arangoproxy-frontend:
    container_name: arangoproxy-frontend
    image: arangoproxy
    build:
      context: .
      target: arangoproxy
    networks:
      docs_net:
        ipv4_address: 192.168.129.129
    volumes:
      - ../../:/home/
    environment:
      - HUGO_URL
      - HUGO_ENV

networks:
  docs_net:
    driver: bridge
    name: docs_net