version: "3.5"
services:
  toolchain:
    container_name: toolchain
    image: toolchain
    build:
      context: .
      target: toolchain
    volumes:
      - ${ARANGODB_SRC:-/dev/null}:${ARANGODB_SRC:-/dev/null}
      - ${ARANGODB_SRC_2:-/tmp/1}:${ARANGODB_SRC_2:-/tmp/1}
      - ${ARANGODB_SRC_3:-/tmp/2}:${ARANGODB_SRC_3:-/tmp/2}
      - ${ARANGODB_SRC_4:-/tmp/3}:${ARANGODB_SRC_4:-/tmp/3}
      - ../../:/home/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ENV: ${ENV:-local}
      HUGO_URL: ${HUGO_URL:-http://localhost}
      HUGO_ENV: ${HUGO_ENV:-development}
      GENERATORS: ${GENERATORS}
      ARANGODB_SRC_3_10: ${ARANGODB_SRC_3_10}
      ARANGODB_SRC_3_11: ${ARANGODB_SRC_3_11}
      ARANGODB_SRC_3_12: ${ARANGODB_SRC_3_12}
      ARANGODB_SRC_3_13: ${ARANGODB_SRC_3_13}
      ARANGODB_BRANCH_3_10: ${ARANGODB_BRANCH_3_10}
      ARANGODB_BRANCH_3_11: ${ARANGODB_BRANCH_3_11}
      ARANGODB_BRANCH_3_12: ${ARANGODB_BRANCH_3_12}
      ARANGODB_BRANCH_3_13: ${ARANGODB_BRANCH_3_13}
